upstream predia_backend_demo {
  least_conn;
  server predia-api-demo-1:3000 max_fails=3 fail_timeout=10s;
  server predia-api-demo-2:3000 max_fails=3 fail_timeout=10s;
}

server {
  listen 80;
  server_name _;
  client_max_body_size 8m;

  location / {
    proxy_pass http://predia_backend_demo;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto http;
    proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
  }
}

