version: "3.9"

services:
  diabetes-ai:
    build: .
    container_name: diabetes-ai-podman
    ports:
      - "3001:3000"
    restart: unless-stopped
    networks:
      - predia-net-podman

  n8n:
    image: docker.io/n8nio/n8n:latest  # registry explícito
    container_name: predia-n8n-podman
    ports:
      - "5679:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5679/
      - GENERIC_TIMEZONE=America/Mexico_City
      - TZ=America/Mexico_City
    volumes:
      - n8n_data_podman:/home/node/.n8n
    restart: unless-stopped
    networks:
      - predia-net-podman

networks:
  predia-net-podman:
    driver: bridge

volumes:
  n8n_data_podman:
    driver: local